#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "token.h"
#include "helper.h"

// Generated by scanner.flex
extern FILE *yyin;   // Input file for the scanner to use.
extern int yylex();  // Scans text, returns 0 on EOF.
extern int yylineno; // Line number of the last scanned text.
extern char *yytext; // Actual text scanned

void run_scan(const char *filename);

int main(int argc, char *argv[])
{
    if (argc < 3)
    {
        fprintf(stderr, "Usage: %s -scan sourcefile.bminor\n", argv[0]);
        exit(1);
    }

    const char *option = argv[1];
    const char *filename = argv[2];

    if (strcmp(option, "-scan") == 0)
    {
        run_scan(filename);
    }
    else
    {
        fprintf(stderr, "Unknown option: %s\n", option);
        exit(1);
    }

    return 0;
}

void run_scan(const char *filename)
{
    // TODO: Implement the scanner
    yyin = fopen(filename,"r"); 
    token_t textToken = yylex();
    while(textToken != TOKEN_EOF){ 
    if(textToken == TOKEN_ERROR)
    { 
        printf("Scan Error: Unexpected character '%s' at line %d", yytext, yylineno); 
        break; 
    }
    else 
    { 
        printf("%s: %s\n", TokenList[textToken], yytext);
    }
    }
    fclose(yyin);
}
