# The top level rule indicates how to link everything together into bminor.
# Add a rule for each file that needs to be compiled.

bminor: main.o scanner.o helper.o
	gcc $^ -o bminor	

%.o: %.c *.h
	gcc -Wall -g -c $< -o $@

# Only the files generated by flex need explicit rules.

scanner.c: scanner.flex
	flex -o scanner.c scanner.flex

# clean causes all intermediate files to be deleted.

clean:
	rm -f scanner.c *.o bminor